// Languages
export const CodeLanguages = {
  plaintext: "Plain Text",
  vbnet: ".NET",
  bash: "Bash",
  c: "C",
  coffeescript: "CoffeeScript",
  cpp: "C++",
  csharp: "C#",
  css: "CSS",
  go: "Go",
  graphql: "GraphQL",
  groovy: "Groovy",
  html: "HTML",
  java: "Java",
  js: "JavaScript",
  json: "JSON",
  delphi: "Pascal",
  perl: "Perl",
  php: "PHP",
  python: "Python",
  r: "R",
  ruby: "Ruby",
  rust: "Rust",
  scala: "Scala",
  sql: "SQL",
  ts: "TypeScript",
  xml: "XML",
  yaml: "YAML",
};
